export const QUESTIONS = [
  {},
  {
    label: "How old is your dog?",
    example: "",
    key: "fermented",
    picture: "kombucha.png",
    multiple: false,
    options: [
      {
        label: "Puppy (0-1 year)",
        value: "Puppy (0-1 year)",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Adult (1-7 years)",
        value: "Adult (1-7 years)",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Senior (7+ years)",
        value: "Senior (7+ years)",
        points: 1,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "Is your dog primarily indoors or outdoors?",
    example: "",
    key: "weight gain",
    picture: "gain-weight.png",
    multiple: false,
    options: [
      {
        label: "Indoors",
        value: "Indoors",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Outdoors",
        value: "Outdoors",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Both equally",
        value: "Both equally",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "How much does your dog shed?",
    example: "",
    key: "show",
    picture: "diet.png",
    multiple: false,
    options: [
      {
        label: "Barely sheds",
        value: "Barely sheds",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Moderate shedding",
        value: "Moderate shedding",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Heavy shedding",
        value: "Heavy shedding",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "It feels like I live in a fur storm",
        value: "It feels like I live in a fur storm",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "How often do you brush your dog?",
    example: "",
    key: "show",
    picture: "symptoms.png",
    multiple: false,
    options: [
      {
        label: "Never",
        value: "Never",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Rarely",
        value: "Rarely",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Weekly",
        value: "Weekly",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Daily",
        value: "Daily",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },

  {
    label:
      "Which of the following have you tried to manage your dog's shedding?",
    example: "",
    key: "sleep",
    picture: "energy.png",
    multiple: true,
    options: [
      {
        label: "Brushing regularly",
        value: "Brushing regularly",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Using de-shedding tools",
        value: "Using de-shedding tools",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Feeding special food or supplements",
        value: "Feeding special food or supplements",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Bathing with anti-shedding shampoos",
        value: "Bathing with anti-shedding shampoos",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Professional grooming",
        value: "Professional grooming",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Nothing yet",
        value: "Nothing yet",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "How often do you bathe your dog?",
    example: "",
    key: "climb",
    picture: "fast-food.png",
    multiple: false,
    options: [
      {
        label: "Weekly",
        value: "Weekly",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Monthly",
        value: "Monthly",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Rarely",
        value: "Rarely",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Never",
        value: "Never",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },

  {
    label: "Does your dog's coat look dull or dry?",
    example: "",
    key: "movements",
    picture: "gender.png",
    multiple: false,
    options: [
      {
        label: "Yes",
        value: "Yes",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "No",
        value: "No",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Sometimes",
        value: "Sometimes",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "I'm not sure",
        value: "I'm not sure",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },

  {
    label: "What shedding issues bother you the most?",
    example: "",
    key: "movements",
    picture: "gender.png",
    multiple: true,
    options: [
      {
        label: "Fur on furniture and clothes",
        value: "Fur on furniture and clothes",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Allergies",
        value: "Allergies",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Constant vacuuming",
        value: "Constant vacuuming",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Fur clumps around the house",
        value: "Fur clumps around the house",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "My dog's coat looks unhealthy",
        value: "My dog's coat looks unhealthy",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
];
