export const QUESTIONS = [
  {},
  {
    label: "How old is your dog?",
    example: "",
    key: "fermented",
    picture: "kombucha.png",
    multiple: false,
    options: [
      {
        label: "Puppy (0-1 year)",
        value: "Puppy (0-1 year)",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Adult (1-7 years)",
        value: "Adult (1-7 years)",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Senior (7+ years)",
        value: "Senior (7+ years)",
        points: 1,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "Is your dog primarily indoors or outdoors?",
    example: "",
    key: "weight gain",
    picture: "gain-weight.png",
    multiple: false,
    options: [
      {
        label: "Indoors",
        value: "Indoors",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Outdoors",
        value: "Outdoors",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Both equally",
        value: "Both equally",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "How much does your dog shed?",
    example: "",
    key: "show",
    picture: "diet.png",
    multiple: false,
    options: [
      {
        label: "Barely sheds",
        value: "Barely sheds",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Moderate shedding",
        value: "Moderate shedding",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Heavy shedding",
        value: "Heavy shedding",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "It feels like I live in a fur storm",
        value: "It feels like I live in a fur storm",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "How often do you brush your dog?",
    example: "",
    key: "show",
    picture: "symptoms.png",
    multiple: false,
    options: [
      {
        label: "Never",
        value: "Never",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Rarely",
        value: "Rarely",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Weekly",
        value: "Weekly",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Daily",
        value: "Daily",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },

  {
    label:
      "Which of the following have you tried to manage your dog's shedding?",
    example: "",
    key: "sleep",
    picture: "energy.png",
    multiple: true,
    options: [
      {
        label: "Brushing regularly",
        value: "Brushing regularly",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Using de-shedding tools",
        value: "Using de-shedding tools",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Feeding special food or supplements",
        value: "Feeding special food or supplements",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Bathing with anti-shedding shampoos",
        value: "Bathing with anti-shedding shampoos",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Professional grooming",
        value: "Professional grooming",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Nothing yet",
        value: "Nothing yet",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {
    label: "Do you sometimes tend to...",
    example: "",
    key: "climb",
    picture: "fast-food.png",
    multiple: true,
    options: [
      {
        label: "Overeat",
        value: "Overeat",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Stress eat",
        value: "Stress eat",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Eat irregularly",
        value: "Eat irregularly",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "Eat fast food",
        value: "Eat fast food",
        points: 0,
        icon: "",
        link: "",
      },
      {
        label: "None of the above",
        value: "None of the above",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  // 8 insertion
  {},
  {
    label: "Chose your gender",
    example: "",
    key: "movements",
    picture: "gender.png",
    multiple: false,
    options: [
      {
        label: "Female",
        value: "Female",
        points: 1,
        icon: "",
        link: "",
      },
      {
        label: "Male",
        value: "Male",
        points: 0,
        icon: "",
        link: "",
      },
    ],
  },
  {},
  {},
  {},
];
