export const REVIEWS = [
  {
    title: "A lifesaver for my couch!",
    content:
      "My dog used to shed like crazy, and I had to vacuum every single day. After using this cream for just a week, the shedding has almost completely stopped! My couch is finally staying clean. I'm so happy I found this product. Thank you, Biopeta!",
    name: "Sarah W.",
    picture: "user2.svg",
    country: "California",
    pictureFull: "/dog1.jpg",
    time: "about 3 days ago",
    product: 3,
    stars: 5,
  },
  {
    title: "It actually works!",
    content:
      "I've tried so many products for shedding, but nothing worked until this. I was skeptical at first, but within two weeks, I noticed way less hair around the house. Even my groomer asked what I'm doing differently. Highly recommend!",
    name: "Jake P.",
    picture: "user3.svg",
    country: "New York",
    pictureFull: "/dog2.jpg",
    time: "about 5 days ago",
    product: 6,
    stars: 5,
  },
  {
    title: "No more hair everywhere!",
    content:
      "This cream is amazing! My golden retriever sheds a lot, and it was a nightmare during shedding season. After using this for a month, it's like a miracle. Her coat looks shinier too. Love it!",
    name: "Emily R.",
    picture: "user1.svg",
    country: "Florida",
    pictureFull: "/dog3.jpg",
    time: "about 7 days ago",
    product: 3,
    stars: 5,
  },
  {
    title: "Easy to use and smells nice",
    content:
      "I love how easy it is to apply this cream. My dog doesn't mind it at all, and it smells so much better than other products I've tried. The shedding has gone down a lot, and her fur feels softer too!",
    name: "Michael T.",
    picture: "user2.svg",
    country: "Texas",
    pictureFull: "/dog4.jpg",
    time: "about 10 days ago",
    product: 1,
    stars: 5,
  },
  {
    title: "Really impressed",
    content:
      "I have two huskies, and shedding is just part of my life. I wasn't expecting miracles, but this cream really surprised me. I've seen a big difference, and brushing them is so much easier now.",
    name: "Laura H.",
    picture: "user3.svg",
    country: "Oregon",
    pictureFull: "/dog5.jpg",
    time: "about 2 weeks ago",
    product: 6,
    stars: 5,
  },
  {
    title: "Great for sensitive skin",
    content:
      "My lab has sensitive skin, so I was nervous about trying something new. But this cream didn't cause any irritation, and it really helped with the shedding. His coat looks amazing now. Thank you, Biopeta!",
    name: "Tom L.",
    picture: "user1.svg",
    country: "Colorado",
    pictureFull: "/dog6.jpg",
    time: "about 3 weeks ago",
    product: 6,
    stars: 5,
  },
  {
    title: "Wish I found this sooner!",
    content:
      "I've been battling dog hair for years, and this cream has been a game-changer. My corgi's shedding is finally under control, and the house feels so much cleaner. I'm telling all my friends about this product!",
    name: "Anna K.",
    picture: "user2.svg",
    country: "Washington",
    pictureFull: "/dog7.jpg",
    time: "about 1 month ago",
    product: 3,
    stars: 5,
  },
];
